---
- name: Get Internet Gateway facts
  include_role:
    name: aws_manage_igws
    tasks_from: "get_internet_gateway_facts"
  vars:
    vpc_igw_tag: "{{ igw.aws_igw_name }}"

- name: Delete Internet Gateway {{ igw.aws_igw_name }}
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ igw.aws_igw_region }}"
    vpc_id: "{{ igw_facts.internet_gateways[0].attachments[0].vpc_id }}"
    state: absent
  when: igw_facts.internet_gateways != []
...
